In [2]:
import numpy as np
import sympy as sy

Apakah [1,3] adalah eigenvector dari [[1,-1],[6,-4]]? Jika iya, berapakah eigenvalue-nya?

In [12]:
a = np.array([[1,-1],
              [6,-4]])

eigVal,eigVec=np.linalg.eig(a)

In [16]:
eigVal #eigen value

array([-1., -2.])

In [15]:
eigVec #eigen vector

array([[0.4472136 , 0.31622777],
       [0.89442719, 0.9486833 ]])

[1,3] bukan eigenvector dari [[1,-1],[6,-4]].

Eigenvaluenya adalah [-1., -2.]

### Pembuktian eigenvec dan eigenvalue jika dibalik pengerjaannya

Rumus = eigen vektor * (diagonal eigen value) * (invers eigen vector)

V.diag(lambda).V(invers)

In [14]:
B = eigVec.dot(np.diag(eigVal)).dot(np.linalg.inv(eigVec))
B

array([[ 1., -1.],
       [ 6., -4.]])

In [19]:
np.fliplr(np.diag(eigVal)) #buat ngeflip
np.diag(eigVal)

array([[-1.,  0.],
       [ 0., -2.]])